FROM isaac_ros_dev-aarch64

RUN apt-get update && \
    apt-get install -y \
        ros-humble-isaac-ros-visual-slam \
        ros-humble-isaac-ros-examples \
        ros-humble-isaac-ros-realsense && \
    rm -rf /var/lib/apt/lists/*
